# Generated by Django 4.2.7 on 2025-06-05 11:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectif', models.DecimalField(decimal_places=2, help_text='Montant objectif en euros', max_digits=10)),
                ('montant_actuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('FINANCE', 'Financé'), ('ECHOUE', 'Échoué')], default='EN_COURS', max_length=10)),
                ('date_limite', models.DateTimeField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('porteur', models.ForeignKey(limit_choices_to={'role': 'PORTEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='projets_portes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'db_table': 'projects',
                'ordering': ['-date_creation'],
            },
        ),
    ]
