# Generated by Django 5.1.2 on 2025-06-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
