# Generated by Django 5.1.2 on 2025-06-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adresse',
            field=models.CharField(blank=True, help_text='Adresse complète du projet', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='business_plan',
            field=models.FileField(blank=True, help_text='Business plan du projet', null=True, upload_to='projects/documents/'),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude du projet', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude du projet', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_juridique',
            field=models.FileField(blank=True, help_text='Plan juridique et réglementaire du projet', null=True, upload_to='projects/documents/'),
        ),
    ]
