# Generated by Django 5.1.2 on 2025-06-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_adresse_project_business_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('EN_COURS', 'En cours'), ('FINANCE', 'Financé'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE_VALIDATION', max_length=25),
        ),
    ]
