# Generated by Django 4.2.7 on 2025-06-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Latitude du projet', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Longitude du projet', max_digits=15, null=True),
        ),
    ]
