# Generated by Django 4.2.7 on 2025-06-05 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_investissement', models.DateTimeField(default=django.utils.timezone.now)),
                ('methode_paiement', models.CharField(choices=[('CARTE', 'Carte de crédit')], default='CARTE', max_length=10)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=12)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('investisseur', models.ForeignKey(limit_choices_to={'role': 'INVESTISSEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='projects.project')),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'db_table': 'investments',
                'ordering': ['-date_investissement'],
            },
        ),
    ]
